######################################################################
# Automatically generated by qmake (3.0) Tue Dec 6 23:25:42 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Restklassenmaker
INCLUDEPATH += .

# Input
SOURCES += main.cpp
