######################################################################
# Automatically generated by qmake (3.0) Sat Dec 10 20:47:27 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Restklassenmaker
INCLUDEPATH += .

# Input
HEADERS += Main_Generator.h
SOURCES += main.cpp Main_Generator.cpp
