######################################################################
# Automatically generated by qmake (3.0) Mon Dec 12 11:29:39 2016
######################################################################

QT += widgets
TEMPLATE = app
TARGET = Restklassenmaker
INCLUDEPATH += .
RC_FILE = App.rc

# Input
HEADERS += canvas.h Main_Generator.h
SOURCES += canvas.cpp main.cpp Main_Generator.cpp
